### ISSUE TITLE
How to use ReadRDO

### ISSUE THREAD

**Issue by ruiyun-zhong** [ZhoufangErqiangu/RobotInterface#1]
This is my code:

QVariantList parameters;
int result = m_pFRRJIFLib->dynamicCall("ReadRDO(int, QVariantList*&, int)", 1, parameters, 8).toBool();

when i debug the program An error occurred：
QAxBase: Error calling IDispatch member ReadRDO: Type mismatch in parameter 1 

Can you help me with this problem?

**Comment by ZhoufangErqiangu** [comment]
plz read doc first.

might like bellow.

```
// define your buff here
QVariantList params;

params<<1<<*buffer<<8;
bool result = object->dynamicCall("ReadRDO(int, QVariantList*&, int)", params).toBool();
```
